# Generated by Django 4.2.7 on 2023-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.CharField(max_length=300),
        ),
    ]
