# Generated by Django 4.2.7 on 2023-11-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('starting_year', models.IntegerField(max_length=200)),
                ('ending_year', models.IntegerField(max_length=200)),
                ('university', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('starting_year', models.IntegerField(max_length=200)),
                ('ending_year', models.IntegerField(max_length=200)),
                ('university', models.CharField(max_length=200)),
            ],
        ),
    ]
