# Generated by Django 4.2.7 on 2023-11-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_educations_ending_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='ending_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='starting_year',
            field=models.IntegerField(),
        ),
    ]
