# Generated by Django 4.2.7 on 2023-11-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_experiences_ending_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
