# Generated by Django 4.2.7 on 2023-11-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
