# Generated by Django 4.2.7 on 2023-11-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_testimonial_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
