# Generated by Django 4.2.7 on 2023-11-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
