# Generated by Django 4.2.7 on 2023-11-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
