# Generated by Django 4.2.7 on 2023-11-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
